ci: fix typo at build-report.yml

diff --git a/.github/workflows/build-report.yml b/.github/workflows/build-report.yml
--- a/.github/workflows/build-report.yml
+++ b/.github/workflows/build-report.yml
@@ -69,7 +69,7 @@ jobs:
           fi
           
           if [[ "$SCOPES" != *"repo"* ]]; then
-            echo ""\e[91m❌ Error: missing scope 'repo' on the PAT.\e[0m" >&2
+            echo "\e[91m❌ Error: missing scope 'repo' on the PAT.\e[0m" >&2
             log_pat_error
             exit 1
           fi
